name: 🚀 Deploy the website

on:
  push:
    branches: [master, main]
    paths: [web/**, .github/workflows/website.yml]

concurrency:
  group: ${{ github.ref }}-website
  cancel-in-progress: true

jobs:
  update:
    name: 🖼 Deploy the website
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with: {path: web}

      - {uses: actions/deploy-pages@v1, id: deployment}
